Repository TripalCultivate/TripalCultivate-Phenotypes, pull requests merged in 2023-07, with the labels that each got.

#29 Build our own dockerfile with testchado schema name.
  .github/workflows/ALL-PHPUnit.yml
  .github/workflows/MAIN-phpunit-Grid1A.yml
  .github/workflows/MAIN-phpunit-Grid1B.yml
  .github/workflows/MAIN-phpunit-Grid2A.yml
  .github/workflows/MAIN-phpunit-Grid2B.yml
  .github/workflows/MAIN-phpunit-Grid2C.yml
  .github/workflows/MAIN-phpunit-Grid2D.yml
  .github/workflows/MAIN-phpunit-Grid3C.yml
  .github/workflows/MAIN-phpunit-Grid3D.yml
  Dockerfile
Labels: Group 5 | Automated Testing | Performance

#13 G4.12 Term Service
  trpcultivate_phenotypes/config/install/trpcultivate_phenotypes.settings.yml
  trpcultivate_phenotypes/config/schema/trpcultivate_phenotypes.schema.yml
  trpcultivate_phenotypes/src/Service/TripalCultivatePhenotypesTermsService.php
  trpcultivate_phenotypes/tests/src/Functional/InstallTest.php
  trpcultivate_phenotypes/tests/src/Kernel/ServiceTermTest.php
  trpcultivate_phenotypes/trpcultivate_phenotypes.module
  trpcultivate_phenotypes/trpcultivate_phenotypes.services.yml
Labels: Group 4 - API | Services | Plugins

#33 Use new noChado Tripaldocker images.
  Dockerfile
Labels: Group 0 - General, bug - confirmed
